cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

config/urls.py
# config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('social_django.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('chat/', include('chat.urls')),
    path('kakaopay/', include('kakaopay.urls', namespace='kakaopay')),
    path('', include('market.urls', namespace='market')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
#user\urls.py
from django.conf import settings
from django.conf .urls.static import static
from django.urls import path
from django.contrib.auth import  views as auth_views
from . import views

app_name = 'user'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('login/#', views.signup, name='signup'),
    path('profile/', views.profile, name='profile'),
    path('my_products/', views.my_products, name='my_products'),
    path('my_products/<str:category_slug>/', views.my_products, name='my_product_list_filtered'),
    path('delete/', views.UserDeleteView.as_view(), name='delete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_image = models.ImageField(upload_to='profile_images/%Y/%m/%d/', blank=True, null=True)

    def __str__(self):
        return self.user.username

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import UserProfile

class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")
    profile_image = forms.ImageField(label="프로필 이미지", required=False)

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email", "profile_image")

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['profile_image']

user/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404

from market.models import Category, Product
from user.forms import UserForm
from .models import UserProfile
from .forms import UserProfileForm
from django.contrib.auth.models import User
from django.views.generic.edit import DeleteView
from django.urls import reverse_lazy

def login_success(request):
    username = request.user  # 현재 로그인된 사용자의 이름 가져오기
    return render(request, 'market/home.html', {'username': username})

def logout_view(request):
    logout(request)
    return redirect('market:home')

def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST, request.FILES) # 파일 업로드 처리 추가
        if form.is_valid():
            user = form.save()
            profile_image = form.cleaned_data.get('profile_image')
            user_profile = UserProfile(user=user, profile_image=profile_image)
            user_profile.save()

            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인
            return redirect('market:home')
    else:
        form = UserForm()
    return render(request, 'user/login.html', {'form': form})

def profile(request):
    try:
        user_profile = UserProfile.objects.get(user=request.user)
    except UserProfile.DoesNotExist:
        user_profile = None

    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES, instance=user_profile)
        if form.is_valid():
            form.save()
            return redirect('user:profile')
    else:
        form = UserProfileForm(instance=user_profile)

    return render(request, 'user/profile.html', {'user_profile': user_profile})

@login_required
def my_products(request, category_slug=None):
    user = request.user
    category = None
    products = Product.objects.filter(user=user).order_by('-created')

    categories = Category.objects.all()
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category).order_by('-created')

    return render(request, 'user/profile/my_products.html', {
        'products': products,
        'category': category,
        'categories': categories,
    })

class UserDeleteView(DeleteView):
    model = User
    success_url = reverse_lazy('market:home')  # 성공 후 리다이렉트할 URL

    def get_object(self, queryset=None):
        return self.request.user

user/templates/user/form_errors.html
<!--form_errors.html-->
{% if form.errors %}
    <div class="alert alert-danger">
        {% for field in form%}
            {%if field.errors%}
                <div>
                    <strong>{{ field.label }}</strong>
                    {{ field.errors }}
                </div>
            {% endif %}
        {% endfor %}
        <!--넌 필드 오류-->
        {% for error in form.non_field_errors %}
            <div>
                <strong>{{ error }}</strong>
            </div>
        {% endfor %}
    </div>
{% endif %}

user/templates/user/login.html
{% extends "market/base.html" %}
{% load socialaccount %}
{% load static %}
{% block content %}

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
      integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
<head>
    <link href="{% static 'css/component.css' %}" rel="stylesheet"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet"/>
</head>

  <style type="text/css">
       body{
      margin: 0;
      padding: 0;
      color:#B67356;
      background:#EABEAB;
      font:400 16px/18px 'Open Sans',sans-serif;
    }
    *,:after,:before{box-sizing:border-box}
    .clearfix:after,.clearfix:before{content:'';display:table}
    .clearfix:after{clear:both;display:block}
    a{color:inherit;text-decoration:none}

    .login-wrap{
      width:100%;
      margin:auto;
      max-width:525px;
      min-height:680px;
      position:relative;
      background:#E8AD92 no-repeat center;
      box-shadow:0 12px 15px 0 rgba(0,0,0,.24),0 17px 50px 0 rgba(0,0,0,.19);
    }
    .login-html{
      width:100%;
      height:100%;
      position:absolute;
      padding:90px 70px 50px 70px;
      background:rgba(118, 55, 26,.9);
    }
    .login-html .sign-in-htm,
    .login-html .sign-up-htm{
      top:0;
      left:0;
      right:0;
      bottom:0;
      position:absolute;
      transform:rotateY(180deg);
      backface-visibility:hidden;
      transition:all .4s linear;
    }
    .login-html .sign-in,
    .login-html .sign-up,
    .login-form .group .check{
      display:none;
    }
    .login-html .tab,
    .login-form .group .label,
    .login-form .group .button{
      text-transform:uppercase;
    }
    .login-html .tab{
      font-size:22px;
      margin-right:15px;
      padding-bottom:5px;
      margin:0 15px 10px 0;
      display:inline-block;
      border-bottom:2px solid transparent;
    }
    .login-html .sign-in:checked + .tab,
    .login-html .sign-up:checked + .tab{
      color:#fff;
      border-color:#9B5F44;
    }
    .login-form{
      min-height:345px;
      position:relative;
      perspective:1000px;
      transform-style:preserve-3d;
    }
    .login-form .group{
      margin-bottom:15px;
    }
    .login-form .group .label,
    .login-form .group .input,
    .login-form .group .button{
      width:100%;
      color:#fff;
      display:block;
    }
    .login-form .group .input,
    .login-form .group .button{
      border:none;
      padding:15px 20px;
      border-radius:25px;
      background:rgba(255,255,255,.1);
    }
    .login-form .group input[data-type="password"]{
      text-security:circle;
      -webkit-text-security:circle;
    }
    .login-form .group .label{
      color:#aaa;
      font-size:12px;
    }
    .login-form .group .button{
      background:#9B5F44;
    }
    .login-form .group label .icon{
      width:15px;
      height:15px;
      border-radius:2px;
      position:relative;
      display:inline-block;
      background:rgba(255,255,255,.1);
    }
    .login-form .group label .icon:before,
    .login-form .group label .icon:after{
      content:'';
      width:10px;
      height:2px;
      background:#fff;
      position:absolute;
      transition:all .2s ease-in-out 0s;
    }
    .login-form .group label .icon:before{
      left:3px;
      width:5px;
      bottom:6px;
      transform:scale(0) rotate(0);
    }
    .login-form .group label .icon:after{
      top:6px;
      right:0;
      transform:scale(0) rotate(0);
    }
    .login-form .group .check:checked + label{
      color:#fff;
    }
    .login-form .group .check:checked + label .icon{
      background:#1161ee;
    }
    .login-form .group .check:checked + label .icon:before{
      transform:scale(1) rotate(45deg);
    }
    .login-form .group .check:checked + label .icon:after{
      transform:scale(1) rotate(-45deg);
    }
    .login-html .sign-in:checked + .tab + .sign-up + .tab + .login-form .sign-in-htm{
      transform:rotate(0);
    }
    .login-html .sign-up:checked + .tab + .login-form .sign-up-htm{
      transform:rotate(0);
    }

    .hr{
      height:2px;
      margin:60px 0 50px 0;
      background:rgba(255,255,255,.2);
    }
    .foot-lnk{
      text-align:center;
    }
    </style>
{% include "user/form_errors.html" %}
<div class="login-wrap">
  <div class="login-html">
    <input id="tab-1" type="radio" name="tab" class="sign-in" checked><label for="tab-1" class="tab">Sign In</label>
    <input id="tab-2" type="radio" name="tab" class="sign-up"><label for="tab-2" class="tab">Sign Up</label>
    <div class="login-form">
      <div class="sign-in-htm">
          <form action="{% url 'user:login' %}" method="post">
              {% csrf_token %}
        <div class="group">
          <label for="username" class="label">ID</label>
          <input id="username" type="text" class="input"
                 name="username" id="username" value="{{form.username.value|default_if_none:''}}">
        </div>
        <div class="group">
          <label for="password" class="label">Password</label>
          <input id="password" type="password" class="input"
                 name="password" id="password" data-type="password" value="{{form.password.value|default_if_none:''}}">
        </div>
              <div class="group">
          <button type="submit" class="button">로그인</button>
          </div>
          </form>
        <div class="hr"></div>
        <a href="{% provider_login_url 'kakao' %}">
            <img src="{% static 'img/kakao_login.png' %}" alt="..." height="45" width="180" style="margin-left:10px;">
          </a>
        <a href="{% url 'social:begin' 'naver' %}">
             <img src="{% static 'img/naver_login.png' %}" alt="..." height="45" width="180" style="border-radius: 6.5px;">
        </a>
        <a href="{% url 'social:begin' 'google-oauth2' %}" class="d-flex justify-content-center">
            <img src="{% static 'img/google_login.png' %}" alt="Google Login" style="margin-top: 10px;">
        </a>
        <div class="foot-lnk">
        </div>
      </div>
      <div class="sign-up-htm">
          <form method="post" action="{% url 'user:signup' %}" enctype="multipart/form-data">
                {% csrf_token %}
        <div class="group">
          <label for="username" class="label">ID</label>
          <input id="username" type="text" class="input"
          name="username" id="username"
                    value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="group">
          <label for="password1" class="label">Password</label>
          <input id="password" type="password" class="input" data-type="password"
           name="password1" id="password1"
                           value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="group">
          <label for="password2" class="label">Repeat Password</label>
          <input id="password" type="password" class="input" data-type="password"
          name="password2" id="password2"
                           value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="group">
          <label for="email" class="label">Email Address</label>
          <input id="pass" type="text" class="input"
           name="email" id="email"
                           value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
          <label for="profile_image">프로필 이미지</label>
          <input type="file" class="form-control" name="profile_image" id="profile_image">
        </div>
        <div class="group">
          <input type="submit" class="button" value="Sign Up">
        </div>
        </form>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Footer -->
<footer class="py-5 bg-light">
  <div class="container">
     <p class="m-0 text-center text-black">Copyright &copy; team 27.5</p>
  </div>
</footer>

{% endblock %}

user/templates/user/profile.html
{% extends "market/base.html" %}
{% load static %}
{% block title %}
    Profile
{% endblock %}
{% block content %}
 <style>
        /* 전체 컨텐츠를 중앙 정렬하기 위한 스타일 */
        .content-container {
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            height: 100vh; /* 화면 전체 높이에 맞춰 세로 중앙 정렬 */
            text-align: center;
            position: relative;
            overflow: hidden; /* 가상 요소가 넘치지 않도록 설정 */
        }

        /* 가상 요소 스타일 */
        .content-container::before,
        .content-container::after {
            content: "";
            position: absolute;
            top: 0;
            height: 100%;
            z-index: -1; /* 실제 컨텐츠 뒤로 이동 */
        }

        /* 왼쪽 여백 스타일 */
        .content-container::before {
            left: 0;
            width: 50%; /* 왼쪽 절반만 색상이 표시됨 */
            background-color: #f1d9cf; /* 왼쪽 배경색 */
        }

        /* 오른쪽 여백 스타일 */
        .content-container::after {
            right: 0;
            width: 50%; /* 오른쪽 절반만 색상이 표시됨 */
            background-color: #a96f5f; /* 오른쪽 배경색 */
        }

        /* 내용 컨테이너 스타일 */
        .content {
            position: relative; /* 가상 요소 위에 위치하도록 설정 */
            z-index: 1; /* 가상 요소 위로 올려줌 */
            background-color: #fff; /* 실제 컨텐츠 배경색 */
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            width: 300px;
            max-width: 800px; /* 컨텐츠 최대 너비 */
            margin: 100px; /* 가운데 정렬 */
            height: 400px; /* 내용에 맞게 높이 자동 조절 */
            max-height: 80vh; /* 최대 높이를 화면 높이의 80%로 제한 */
            overflow-y: auto; /* 내용이 넘칠 경우 스크롤 표시 */
        }

        /* 프로필 이미지 스타일 */
        .profile-image {
            border-radius: 50%;
            margin-bottom: 20px;
        }

    </style>
<div class="content-container">
    <div class="content">
    <h1>Profile</h1>
    <img src="{% if user_profile.profile_image %}
                {{ user_profile.profile_image.url }}
              {% else %}
                {% static 'img/no_image.png' %}
              {% endif %}" class="profile-image" width="150">
    <p>{{ user.email }}</p>
    <a href="{% url 'user:my_products' %}" class="btn btn-outline-dark" style="margin-bottom:15px;">내가 올린 글</a>
    <br>
    <button id="delete-account" class="btn btn-outline-dark">회원탈퇴</button>
    <form id="delete-form" method="post" action="{% url 'user:delete' %}" style="display:none;">
        {% csrf_token %}
    </form>
<script>
document.getElementById('delete-account').addEventListener('click', function() {
    if (confirm('회원을 탈퇴하시겠습니까?')) {
        document.getElementById('delete-form').submit();
    }
});
</script>



{% endblock %}

user/templates/user/signup.html
{% extends "market/base.html" %}
{% block content %}

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
      integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

  <style type="text/css">

    </style>

    <div class="sign-up-htm">
        <form method="post" action="{% url 'user:signup' %}" enctype="multipart/form-data">
        {% csrf_token %}
        {% include "user/form_errors.html" %}
        <div class="group">
          <label for="username">사용자 이름</label>
            <input type="text" class="form-control" name="username" id="username"
            value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="group">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                   value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="group">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                   value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="group">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="profile_image">프로필 이미지</label>
            <input type="file"  name="profile_image" id="profile_image">
        </div>
        <div class="group">
          <input type="submit" class="btn btn-primary" value="Sign Up">
        </div>
        </form>
        <div class="hr"></div>
        <div class="foot-lnk">
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}