cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

chat/urls.py
# chat/urls.py

from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    path('list/', views.chat_list, name='list'),
    path('<str:room_name>/', views.room, name='room'),
]

config/urls.py
# config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('social_django.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('chat/', include('chat.urls')),
    path('kakaopay/', include('kakaopay.urls', namespace='kakaopay')),
    path('', include('market.urls', namespace='market')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

market/urls.py
from django.urls import path
from . import views

app_name = 'market'

urlpatterns = [
    path('', views.home, name='home'),
    path('search/', views.search, name='search'),
    path('<str:category_slug>/create/', views.product_create, name='product_create'),
    path('<str:category_slug>/<str:minicategory_slug>/<int:id>/update/', views.product_update, name='product_update'),
    path('<str:category_slug>/<str:minicategory_slug>/<int:id>/delete/', views.product_delete, name='product_delete'),
    path('<str:category_slug>/', views.product_list, name='product_list'),
    path('<str:category_slug>/<str:minicategory_slug>/', views.product_list, name='product_list_filtered'),
    path('<str:category_slug>/<str:minicategory_slug>/<int:id>/', views.product_detail, name='product_detail'),
]

user/urls.py
#user\urls.py
from django.conf import settings
from django.conf .urls.static import static
from django.urls import path
from django.contrib.auth import  views as auth_views
from . import views

app_name = 'user'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('login/#', views.signup, name='signup'),
    path('profile/', views.profile, name='profile'),
    path('my_products/', views.my_products, name='my_products'),
    path('my_products/<str:category_slug>/', views.my_products, name='my_product_list_filtered'),
    path('delete/', views.UserDeleteView.as_view(), name='delete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

market/models.py
# market/models.py

from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    class Meta:
        ordering = ['name']
        indexes = [models.Index(fields=['name'])]
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('market:product_list', args=[self.slug])

    def get_create_url(self):
        return reverse('market:product_create', args=[self.slug])

class MiniCategory(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    class Meta:
        ordering = ['name']
        indexes = [models.Index(fields=['name'])]
        verbose_name = 'mini_category'
        verbose_name_plural = 'mini_categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('market:product_list_filtered', args=[self.category.slug, self.slug])

class Product(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default=1)
    minicategory = models.ForeignKey(MiniCategory, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, allow_unicode=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d/', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=0)
    latitude = models.FloatField(null=True, blank=True)
    longitude = models.FloatField(null=True, blank=True)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['id', 'slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-created']),
        ]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('market:product_detail', args=[self.category.slug, self.minicategory.slug, self.id])

    def get_update_url(self):
        return reverse('market:product_update', args=[self.category.slug, self.minicategory.slug, self.id])

market/forms.py
# market/forms.py

from django import forms
from .models import Product

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['minicategory', 'name', 'description', 'price', 'latitude', 'longitude', 'image']

market/views.py
# market/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q

from cart.cart import Cart
from cart.forms import CartAddProductForm
from .models import Category, MiniCategory, Product
from .forms import ProductForm
from django.http import HttpResponse, JsonResponse
from django.views.decorators.http import require_POST

def home(request):
    products = Product.objects.order_by('?')

    return render(request, 'market/home.html',
                  {'products':products})

def search(request):
    kw = request.GET.get('kw', '')  # 검색어
    products = Product.objects.order_by('-created')

    if kw:
        products = products.filter(
            Q(name__icontains=kw) |  # 제목 검색
            Q(description__icontains=kw)  # 내용 검색
        ).distinct()

    return render(request, 'market/product/search.html', {'kw':kw, 'products':products})

def product_list(request, category_slug=None, minicategory_slug=None):
    category = None
    categories = Category.objects.all()
    minicategory = None
    minicategories = MiniCategory.objects.all()
    products = Product.objects.filter(available=True).order_by('-created')

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        minicategories = MiniCategory.objects.filter(category=category)
        products = products.filter(category=category)

        if minicategory_slug:
            minicategory = get_object_or_404(MiniCategory, slug=minicategory_slug)
            products =products.filter(minicategory=minicategory)

    return render(request, 'market/product/product_list.html',
                  {
                      'category': category, 'categories': categories,
                      'minicategory': minicategory, 'minicategories': minicategories,
                      'products': products
                  })

def product_detail(request, id, category_slug, minicategory_slug):
    category = None
    categories = Category.objects.all()
    minicategory = None
    minicategories = MiniCategory.objects.all()
    product = get_object_or_404(Product, id=id, available=True)
    cart_product_form = CartAddProductForm()

    if category_slug and minicategory_slug:
        category = get_object_or_404(Category, slug=category_slug)
        minicategory = get_object_or_404(MiniCategory, slug=minicategory_slug)

    return render(request, 'market/product/detail.html',
                  {
                      'category': category, 'categories': categories,
                      'minicategory': minicategory, 'minicategories': minicategories,
                      'product': product, 'cart_product_form': cart_product_form
                  })

@login_required
def product_create(request, category_slug):
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        minicategories = MiniCategory.objects.filter(category=category)

        if request.method == 'POST':
            form = ProductForm(request.POST, request.FILES)
            if form.is_valid():
                product = form.save(commit=False)
                product.user = request.user
                product.category = category
                product.save()
                return redirect('market:product_detail', category_slug=product.category.slug,
                                minicategory_slug=product.minicategory.slug, id=product.id)
        else:
            form = ProductForm()

    return render(request, 'market/product/create.html',
                  {'form': form, 'category': category,
                          'minicategories': minicategories})

@login_required
def product_update(request, category_slug, minicategory_slug, id):
    product = get_object_or_404(Product, category__slug=category_slug, minicategory__slug=minicategory_slug, id=id)

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            return redirect('market:product_detail', category_slug=product.category.slug,
                            minicategory_slug=product.minicategory.slug, id=product.id)
    else:
        form = ProductForm(instance=product)

    category = product.category
    minicategories = MiniCategory.objects.filter(category=category)
    minicategory = product.minicategory

    return render(request, 'market/product/update.html',
                  {'form': form, 'category': category, 'product': product,
                   'minicategories': minicategories, 'minicategory': minicategory})

@login_required
@require_POST
def product_delete(request, category_slug, minicategory_slug, id):
    product = get_object_or_404(Product, category__slug=category_slug, minicategory__slug=minicategory_slug, id=id)
    cart = Cart(request)
    cart.remove_product_by_id(product.id)
    product.delete()
    return JsonResponse({'message': 'Product deleted successfully'}, status=200)

market/templates/market/base.html
<!-- market/templates/market/base.html -->
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- bootstrap -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css'%}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css'%}">
    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>
<body>

<!-- navbar -->
{% include 'market/navbar.html' %}


<div id="content">
    {% block content %}
    {% endblock %}
</div>


<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>

<!-- 자바스크립트 -->
{% block script %}
{% endblock %}
<script type="text/javascript">
    const btn_search = document.getElementById('btn-search');
    btn_search.addEventListener('click', function(){
        document.getElementById('kw').value = document.getElementById('search_kw').value;
        document.getElementById('searchForm').submit();
    });
</script>

</body>
</html>

market/templates/market/home.html
{% extends 'market/base.html' %}
{% load static %}
{% block title %}
    Ant Market
{% endblock %}
{% block content %}
<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Nanum+Myeongjo:wght@700&family=Noto+Serif+KR:wght@200..900&display=swap" rel="stylesheet">


<style type="text/css">
    /* h1 style */
    body {
        background-color: #845f51;
        margin: 0;
        padding: 0;
        min-height: 100vh; /* 최소 높이를 화면 높이로 설정 */
        display: flex;
        flex-direction: column; /* 화면을 수직으로 나열 */
    }

    .content {
        flex: 1; /* 나머지 공간을 차지 */
    }

    h1 {
       text-align: center; /* 중앙 정렬 */
       font-family: 'Nanum Myeongjo', serif; /* Google Font 폰트 변경 */
       font-size: 3em; /* 폰트 크기 조정 */
       color: #333; /* 폰트 색상 변경 (필요에 따라) */
    }

    hr {
      height: 2px;
      overflow: visible;
      color: #999;
      position: relative;
      margin: 1em auto; /* 간격을 좁히기 위해 margin 조정 */
    }

    hr::before {
      content: "";
      background: linear-gradient(to right, transparent, currentColor, transparent);
      height: 2px;
      width: 100%;
      position: absolute;
      left: 0;
    }

    hr[data-content] {
      text-align: center;
      margin-top: 1.5em; /* 요소 전체 아래 이동 */
    }

    hr[data-content]::after {
      content: attr(data-content);
      position: relative;
      background: #845f51;
      padding: 0 1.5rem;
      top: -0.5em;
      font-size: 3em;
      line-height: 1;
      font-family: serif;
      font-style: italic;
      color: currentColor;
    }
</style>
<!--title-->
<h1 style="margin-top:40px; color:#e8d8d3;"><em>Antique</em></h1>
<article class="container">
  <header>
     <hr data-content="&amp;" />
  </header>
<h1 style="margin-top:25px; margin-bottom:-30px; color:#f4e7e0;"><em>Trade</em></h1>
<!--title-->

    <!--캐러셀 슬라이드 css-->
        <style>
          .pics {      /* 전체 케러셀 */
            width: 10px;
            float: left;
            position: relative;
            left: 50%;
            object-fit: cover;
        }

          .carousel-inner {
            display: block;
            margin: 100px 8px 8px;
            width: 100;
            height: 500px; /* 이미지 높이 변경 */
        }

          .carousel-item {
            display: block;
            margin: 0 auto;
            width: 100;
            height: 100%;
        }

          .d-block {
            display: block;
            margin: 0 auto;
            width: 100;
            height: 100%;
        }

        </style>
    <!--캐러셀 슬라이드 css-->
    <!--슬라이더-->
       <head>
         <meta charset="UTF-8" />
         <meta http-equiv="X-UA-Compatible" content="IE=edge" />
         <meta name="viewport" content="width=device-width, initial-scale=1.0" />
         <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" />
      </head>

        <body>
          <div id="carouselExample" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner">
              <div class="carousel-item active" data-bs-interval="5000">
                <img src="static/img/main.png" class="d-block w-40" alt="..." />
              </div>
              <div class="carousel-item" data-bs-interval="5000">
                <img src="static/img/book.png" class="d-block w-40" alt="..." />
              </div>
              <div class="carousel-item" data-bs-interval="5000">
                <img src="static/img/LP.png" class="d-block w-40" alt="..." />
              </div>
            </div>
              <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
              </button>
              <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
              </button>
            </div>
          <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
        </body>
        <!--슬라이더-->

<!--추천제품 섹션-->
    <style>
            h4 {
                display: block;
                font-size: 2em;
                margin-top: 2.5em;
                margin-left: 0;
                margin-right: 0;
                font-weight: bold;
                color: #FFFFFF;
                }
        </style>

        <h4 align="center">추천상품</h4>

        <style type="text/css">
            body {
                background-color: #845f51;
                }


        </style>

        <section class="py-5">
            <div class="container px-4 px-lg-5 mt-5">
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                    {% for product in products|slice:":8" %}
                    <div class="col mb-5">
                            <div class="card h-100">
                                <!-- Product image-->
                                <img class="card-img-top" src="{% if product.image %}
                                                                 {{ product.image.url }}
                                                               {% else %}
                                                                 {% static 'img/no_image.png' %}
                                                               {% endif %}" alt="..." />
                                <!-- Product details-->
                                <div class="card-body p-4">
                                    <div class="text-center">
                                        <!-- Product name-->
                                        <h5 class="fw-bolder">{{ product.name }}</h5>
                                        <!-- Product price-->
                                        {{ product.price }}원
                                    </div>
                                </div>
                                <!-- Product actions-->
                                <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                    <div class="text-center">
                                        <a class="btn btn-outline-dark mt-auto" href="{% url 'market:product_detail' product.category.slug product.minicategory.slug product.id %}">
                                            상세 보기
                                        </a>
                                    </div>
                                </div>
                            </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </section>

<!--추천제품 섹션-->


    <form id="searchForm" method="get" action="{% url 'market:search' %}">
        <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    </form>
<!-- Footer -->
    <footer class="py-5 bg-light">
        <div class="container">
            <p class="m-0 text-center text-black">Copyright &copy; team 27.5</p>
        </div>
    </footer>
{% endblock %}
{% block script %}
<script type="text/javascript">
    const btn_search = document.getElementById('btn-search');
    btn_search.addEventListener('click', function(){
        document.getElementById('kw').value = document.getElementById('search_kw').value;
        document.getElementById('searchForm').submit();
    });
</script>
{% endblock %}

market/templates/market/navbar.html
{% load static %}
<head>
    <link href="{% static 'css/component.css' %}" rel="stylesheet"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet"/>
</head>

<!-- 네비게이션 바 -->

<style type="text/css">
    .navbar {
       position: relative; /* .navbar 요소의 위치 지정을 relative로 설정 */
       display: flex !important;
       justify-content: space-between !important;
       background-color: #FFFFFF !important;
    }
    nav a {
        position: center;
        display: inline-block;
        margin: -3px 0px;
        outline: none;
        color: rgba(0, 0, 0, 1) !important; /*카테고리 내부 글 색상*/
        text-decoration: none;
        text-transform: uppercase;
        text-align: center;
        letter-spacing: 1px;
        font-weight: 400;
        text-shadow: 0 0 1px rgba(255,255,255,0.3);
        font-size: 1em;
    }

    .navbar .nav-item {
        display: flex;
        align-items: center;

    }

    .navbar .nav-link {
        margin-left: -10px;
    }
    .nav-link {
        margin-left: -30px; /* 채팅과 categoryname 사이의 왼쪽 여백 조정 */
        margin-right: -30px; /* 채팅과 categoryname 사이의 오른쪽 여백 조정 */
    }

    nav a:hover,
    nav a:focus {
        outline: none;
    }

    .navbar .nav-link:last-child {
        margin-right: 0; /* 마지막 요소의 오른쪽 여백을 0으로 설정 */
    }

    .nanum-myeongjo-bold {
      font-family: "Nanum Myeongjo", serif;
      font-weight: 700;
      font-style: normal;
    }

    li{
        font-family: "Nanum Myeongjo", serif;
        font-size: 30px;
        color: rgba(0, 0, 0, 1) !important;
        padding: 5px 5px 30px 330px; /*메뉴 항목 위치 조정*/
    }

    .cl-effect-1 a::before,
    .cl-effect-1 a::after {
        display: inline-block;
        opacity: 0;
        -webkit-transition: -webkit-transform 0.3s, opacity 0.2s;
        -moz-transition: -moz-transform 0.3s, opacity 0.2s;
        transition: transform 0.3s, opacity 0.2s;
    }

    .cl-effect-1 a::before {
        margin-right: 10px;
        content: '[';
        -webkit-transform: translateX(20px);
        -moz-transform: translateX(20px);
        transform: translateX(20px);
    }

    .cl-effect-1 a::after {
        margin-left: 10px;
        content: ']';
        -webkit-transform: translateX(-20px);
        -moz-transform: translateX(-20px);
        transform: translateX(-20px);
    }

    .cl-effect-1 a:hover::before,
    .cl-effect-1 a:hover::after,
    .cl-effect-1 a:focus::before,
    .cl-effect-1 a:focus::after {
        opacity: 1;
        -webkit-transform: translateX(0px);
        -moz-transform: translateX(0px);
        transform: translateX(0px);
    }

     .search-form {
        position: absolute;
        top: 30%; /* navbar의 상단을 기준으로 세로 중앙 정렬 */
        right: 20px; /* navbar 오른쪽 여백 */
        transform: translateY(-50%); /* 수직 정렬을 위한 변형 */
    }

    .search-input {
        width: 200px; /* 예시로 너비를 설정 */
    }

    .search-button {
        height: calc(100% - 2px); /* 버튼 높이 조정 */
        border-top-right-radius: 0; /* 버튼 모서리 조정 */
        border-bottom-right-radius: 0;
        font-size: 0.9rem; /* 버튼 글꼴 크기 */
    }
</style>
        <!--navbar-->
        <nav class="navbar">
            <div class="cl-effect-1 px-40 px-lg-5">
                    <a href="{% url 'market:home' %}">
                        <img src="{% static 'img/Ant Market No Bg.png' %}"
                             height="100" width="210" style="margin: 20px 5px -35px 5px">
                    </a>
                </a>

                    <!-- searchform -->
                    <div class="search-form">
                        <div class="input-group search-input">
                            <input type="text" id="search_kw" class="form-control" value="{{ kw|default_if_none:'' }}">
                            <div class="input-group-append">
                                <button class="btn btn-outline-secondary search-button" type="button" id="btn-search">찾기</button>
                            </div>
                        </div>
                    </div>
                    <!-- /searchform -->

                <ul class="nav justify-content-center">
                    <li class="nav-item">
                        {% if user.is_authenticated %}
                            <a class="nav-link" href="{% url 'user:profile' %}">{{ user.username }}</a>
                            <a class="nav-link" href="{% url 'user:logout' %}">로그아웃</a>
                            <!-- chat_list.html로 이동하는 버튼 추가 -->
                            <a class="nav-link" href="{% url 'chat:list' %}">채팅</a>
                        {% else %}
                            <a class="nav-link" href="{% url 'user:login' %}">Login</a>
                        {% endif %}
                    </li>
                    <div style="display: flex; justify-content: flex-end;">
                        <ul class="nav" style="list-style-type: none; padding: 0; margin-left: -20px;">
                            {% for category in categories %}
                                <li style="display: inline-block; margin-left: -20px;">
                                    <a class="nav-link" href="{{ category.get_absolute_url }}">{{ category.name }}</a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </ul>
            </div>
            <!--cart-->
            <div id="subheader">
                <div class="cart d-flex px-4 mt-4">
                    <form action="{% url 'cart:cart_detail' %}" method="get">
                        {% with total_items=cart|length %}
                            {% if total_items > 0 %}
                                <button type="submit" class="btn btn-outline-dark">
                                    장바구니:
                                    {{ total_items }}개 {{ total_items|pluralize }},
                                    {{ cart.get_total_price }}원
                                </button>
                            {% else %}
                                <button type="submit" class="btn btn-outline-dark" style="margin-top:100px; position: absolute; right: 20px; top: 0;">
                                    장바구니가 비어있습니다.
                                </button>
                            {% endif %}
                        {% endwith %}
                    </form>
                </div>
            </div>
            <!--cart-->
                    <form id="searchForm" method="get" action="{% url 'market:search' %}" style="margin-left: auto;">
                        <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
                    </form>
        </nav>